[package]
name = "day3"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
chumsky.workspace = true
common = { path = "../common" }

[dependencies.logos]
workspace = true

[features]
default = []
debug = ["logos/debug"]
